export const getColors = () => [
    {id: "black", value: "#000000"},
    {id: "gray", value: "#808080"},
    {id: "dark-red", value: "#8B0000"},
    {id: "red", value: "#FF0000"},
    {id: "orange", value: "#F87217"},
    {id: "yellow", value: "#FFFF00"},
    {id: "green", value: "#008000"},
    {id: "blue-sky", value: "#3BB9FF"},  
    {id: "blue", value: "#1F45FC"},  
    {id: "purple", value: "#800080"}, 
    {id: "white", value: "#FFFFFF"},
    {id: "silver", value: "#C0C0C0"},   
    {id: "brown", value: "#AF7817"},
    {id: "pink-light", value: "#FAAFBE"},
    {id: "gold", value: "#FBB917"},
    {id: "yellow-light", value: "#FFF8C6"},
    {id: "lime", value: "#8AFB17"},
    {id: "blue-light", value: "#82CAFF"}, 
    {id: "blue-gray", value: "#728FCE"}, 
    {id: "pink", value: "#F535AA"}, 
  ];